
version: '3.0'
services:
  web:
    # TODO: build context, ports and redis dependency
    image: groundnuty/io-lab-docker-ci-public:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    # TODO: missing persistence for redis. You need to persist /data directory.
    volumes:
       - db-data-lab:/data

# Global volume `docker volume ls`       
volumes:
  db-data-lab:
